### ISSUE TITLE
win10上运行演示程序错误

### ISSUE THREAD

**Issue by QQ2017** [imgen/WFPTool#1]
win10上运行演示程序错误：
C:\Users\admin\Desktop\Release>WfpTool
Got a total of 100 filters
Got a total of 100 filters
Got a total of 100 filters
Got a total of 0 filters
Oops, you are not supposed to get error code 680001540
Oops, you are not supposed to get error code 680001539
Got a total of 100 filters
Got a total of 100 filters
Got a total of 100 filters
Got a total of 0 filters

**Comment by imgen** [comment]
I can reproduce this error, will investigate when I have time

**Comment by imgen** [comment]
Also I updated the project to the latest Visual Studio 2022

**Comment by imgen** [comment]
@QQ2017 I have fixed the sample. The error lies in below line of code
```
filterHandle = AddAllowTunnelFilter(L"WFPTool");
```
Here I assume there is an network adapter named `WFPTool` which usually is not the case. I changed it to `Wi-Fi` since most PC has this adapter now

**Comment by imgen** [comment]
@QQ2017 you can use below command to get a list of network adapters
```
netsh interface ipv4 show interfaces
```

**Comment by imgen** [comment]
@QQ2017 you also have to run this `WfpTool.exe` program under admin privilege for it to work
